# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c4413b690e09f2850349b498c79bfdb641900edbf6f28c153aa2b25c8319e2a361287db1c5806406a38f8701b0a2abd59d56ee237b6a566613330c3b2c96475

test:
  secret_key_base: 54ac80797f765799b9ea9eba776c8edc7c655a2d3d95f237d798bb428cd39d46385effc3a5d7f54a1435fdd39ccf460dd13d332bab3bd4ec84ea3111db7e3080

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
